[package]
name = "virtualbutfake/FusionComponents"
description = "A collection of components for Fusion Plugin development"
version = "0.0.269"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "build",
    "build/components",
    "build/components/**",
    "build/theme",
    "build/theme/**",
    "build/init.luau",
    "LICENSE.md",
    "wally.toml",
    "default.project.json",
]
exclude = ["*", "build.rbxl", "build/stories"]
[dependencies]
fusion = "elttob/fusion@0.2.0"
fusionUtils = "virtualbutfake/fusionutils@0.0.144"
tailwind = "virtualbutfake/tailwind@0.0.135"
themeFramework = "virtualbutfake/themeframework@0.0.154"
Lucide = "virtualbutfake/lucide-roblox@1.1.2"
