[package]
name = "virtualbutfake/fusion-components"
description = "A collection of Fusion components"
version = "0.1.18"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "dist",
    "dist/components",
    "dist/components/**",
    "dist/theme",
    "dist/theme/**",
    "dist/init.luau",
    "LICENSE.md",
    "wally.toml",
    "default.project.json",
]
exclude = ["*", "build.rbxm", "dist/stories"]
[dependencies]
fusion = "elttob/fusion@0.2.0"
fusionUtils = "virtualbutfake/fusion-utils@0.1.2"
tailwind = "virtualbutfake/tailwind@0.1.1"
themeFramework = "virtualbutfake/theme-framework@0.1.6"
Lucide = "virtualbutfake/lucide-roblox@1.1.3"
