[package]
name = "virtualbutfake/fusion-components"
description = "A collection of Fusion components"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "build",
    "build/components",
    "build/components/**",
    "build/theme",
    "build/theme/**",
    "build/init.luau",
    "LICENSE.md",
    "wally.toml",
    "default.project.json",
]
exclude = ["*", "build.rbxl", "build/stories"]
[dependencies]
fusion = "elttob/fusion@0.2.0"
fusionUtils = "virtualbutfake/fusion-utils@0.1.0"
tailwind = "virtualbutfake/tailwind@0.1.0"
themeFramework = "virtualbutfake/theme-framework@0.1.0"
Lucide = "virtualbutfake/lucide-roblox@1.1.2"
